name: checkmate

services:
  backend:
    container_name: checkmate-backend
    image: eliashahn12/checkmate-backend:latest
    networks: 
      - main
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

  frontend:
    container_name: checkmate-frontend
    image: eliashahn12/checkmate-frontend:latest
    networks: 
      - main
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  main:
    external: true